### ISSUE TITLE
Удалить пробел перед "]"

### ISSUE THREAD

**Issue by Vadiok** [sopov/rst#1]
Просьба удалить лишний пробел перед "]".
Файл ``parsed/21-esther.dat``, строка 1, конец строки: ``царских. ]``,.

Также, если нетрудно, можно ли изменения в репозиторий помечать тегами версий (v1.0.1 и т.п.), т.к. в таком случае удобнее пользоваться репозиторием через composer (но некритично).

**Comment by sopov** [comment]
На неделе уберу + ``28-sirach.dat`` та же проблема,
можно добавить версионность, но нужен, какой-то скрипт, который будет сам инкриментить файл на пуш (я быстро забуду это делать).

**Comment by sopov** [comment]
1) исправил ошибку
2) почитал про теги (раньше с ними не приходилось работать), вроде добавил, версии пока буду держать по номерам сделанных исправлений, там посмотрим

**Comment by Vadiok** [comment]
Спасибо большое
