### ISSUE TITLE
Отсутствие пробела в "опустошенныхземель" в Иезекииль 30:7 (Русский Синодальный Перевод)

### ISSUE THREAD

**Issue by a1ip** [sopov/rst#4]
Здесь 
https://github.com/sopov/rst/blob/feb6e17c715bf75b7e073dd31a5ff7a03684be23/parsed66/34-ezekiel.dat#L937
и здесь
https://github.com/sopov/rst/blob/feb6e17c715bf75b7e073dd31a5ff7a03684be23/parsed/34-ezekiel.dat#L937
"опустошенных земель" через пробел, но на сайте https://www.bible.ru/ezekiel-30.6/ "опустошенныхземель" без пробела.

**Comment by sopov** [comment]
было исправлено 2 месяца назад, опечатка описана тут https://github.com/sopov/rst/blob/master/issues/031-wrong-text.md , но на сайт пока так и не выкатывал, т.к. работаю над новой версией, там будет всё автоматом из гита забираться (по крайней мере я хочу так сделать).

После этого там ещё пару исправлений было.

Сейчас обновления руками заливаются, и сбрасывается кэш.

на iOS ошибка не исправлена (жду фикса от разарботчиков, эпл не пропускает свежий релиз)
на Андройде хорошо выглядит.
